// Exercise5_AddLayer.cpp : Defines the initialization routines for the DLL.
//

#include "pch.h"
#include "framework.h"
#include"arxHeaders.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif

static void makeLayer()
{
    // Open the Layer table for read 
    AcDbDatabase* pDb = acdbHostApplicationServices()->workingDatabase();
    AcDbLayerTable* pLayerTable;
    pDb->getLayerTable(pLayerTable, AcDb::kForRead);

    // Check to see if the layer exists 
    if (pLayerTable->has(_T("New Layer")) == false)
    {
        // Open the Layer table for write 
        pLayerTable->upgradeOpen();

        // Create the new layer and assign it the name 'OBJ' 
        AcDbLayerTableRecord* pLayerTableRecord =
            new AcDbLayerTableRecord();
        pLayerTableRecord->setName(_T("New Layer"));

        // Set the color of the layer to cyan 
        AcCmColor color;
        color.setColorIndex(4);
        pLayerTableRecord->setColor(color);

        // Add the new layer to the Layer table 
        pLayerTable->add(pLayerTableRecord);

        // Close the Layer table and record 
        pLayerTable->close();
        pLayerTableRecord->close();
    }
}
extern "C" AcRx::AppRetCode acrxEntryPoint(AcRx::AppMsgCode msg, void* pkt)
{
	switch (msg)
	{
	case AcRx::kInitAppMsg:
		acrxDynamicLinker->unlockApplication(pkt);
		acrxDynamicLinker->registerAppMDIAware(pkt);
		acutPrintf(L"\nLoading project...\n");
		// Commands to add
		acedRegCmds->addCommand(_T("AUCommands"), _T("MakeLayer"),
			_T("AddLayer"), ACRX_CMD_MODAL, makeLayer);//addLine  makeLayer
		break;
	case AcRx::kUnloadAppMsg:
		acutPrintf(_T("\nUnloading createLine project...\n"));
		// Command Groups to remove
		acedRegCmds->removeGroup(_T("AUCommnds"));
		break;
	default:
		break;
	}
	return AcRx::kRetOK;
}

